### ISSUE TITLE
Handle security for Elston app-starters

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud-task-app-starters/app-starters-release#49]

**Comment by cppwfs** [comment]
Using https://github.com/spring-cloud-stream-app-starters/core/pull/59/files as a model, this story is still a bit unclear to me.   Stream app starters assume web security is required (app-starters-security-common) .   In tasks we do not support web in the task app starter core(https://github.com/spring-cloud-task-app-starters/core).     It would be a new feature instead of a modification of an existing feature.

**Comment by sabbyanandan** [comment]
We originally wanted this to address a potential gap when launching tasks in K8s; however, it appears the Tasks are _never_ launched to be configured with liveness/readiness probe ports. We [explicitly set the ports to "null"](https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/blob/master/src/main/java/org/springframework/cloud/deployer/spi/kubernetes/KubernetesTaskLauncher.java#L95) (also see [DefaultContainerFactory.java#L72](https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/blob/master/src/main/java/org/springframework/cloud/deployer/spi/kubernetes/DefaultContainerFactory.java#L72)) since they are meant to be a short-lived process in the underlying platform. If we set it, the platform will continue to restart until the probe path/port resolve to success code.

So, yeah, no need to add web/actuator dependencies. We don't need to do the security dance on the Boot 2.1 baseline either. It is business as usual, so I'm closing it.
